### ISSUE TITLE
Help filling in json for new extension

### ISSUE THREAD

**Issue by roidy** [nzbgetcom/nzbget-extensions#14]
>Make your extension compatible with nzbget spec v23+ [coming soon]. Create release with manifest inside (you can use any of nzbgetcom extension as example, e.g [EMail](https://github.com/nzbgetcom/Extension-EMail)).

>"homepage": "https://github.com/nzbgetcom/Extension-NotifyPlex/"

How to fill in homepage info if my extension is new and hasn't been accepted yet,  I wont know what the home page will eventually be?

>Create fork of this repository, add brief information about your extension in JSON format to the "extensions.json" file and submit PR.

>"homepage": "https://github.com/nzbgetcom/Extension-EMail",
"url": "https://github.com/nzbgetcom/Extension-EMail/releases/download/v2.0/email-2.0-dist.zip"

Again how to fill in homepage and url if I don't know what they will be?

**Comment by dnzbk** [comment]
If you are just testing your extension and working with it only locally, you can leave these properties empty.

If you are ready for the official release of your extension and want to add the possibility to install it via Extension Manager then you will need to create the repository `https://github.com/nzbgetcom/Extension-YourExtensionName/`. 
@phnzb can assist you with that. 
A link to this repository would be "homepage".
When you make a release you will get a link to download your extension, e.g. `https://github.com/nzbgetcom/Extension-YourExtensionName/releases/download/v1.0/yourextensionname-1.0-dist.zip`.
This link can be used as "url".
[Extension-FakeDetector](https://github.com/nzbgetcom/Extension-FakeDetector) repository can be considered as an example.
